/*
 * This file (which will be your service worker)
 * is picked up by the build system ONLY if
 * quasar.config file > pwa > workboxMode is set to "InjectManifest"
 *
 * Based on the old site's sw-source.ts - battle tested and working!
 */

/* eslint-disable */
declare const self: any;

import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst } from 'workbox-strategies';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';
import { RangeRequestsPlugin } from 'workbox-range-requests';

// Clean up old caches automatically
cleanupOutdatedCaches();

// Precache all assets generated by Quasar
precacheAndRoute(self.__WB_MANIFEST);

// Cache video files (if any)
registerRoute(
  ({ request }) => {
    const { destination } = request;
    return destination === 'video';
  },
  new CacheFirst({
    plugins: [
      new CacheableResponsePlugin({
        statuses: [200]
      }) as any,
      new RangeRequestsPlugin() as any,
    ],
  }),
);

// Listen for SKIP_WAITING message (CRITICAL - same as old site!)
addEventListener('message', (event) => {
  console.log('SW: Received message:', event.data);
  if (event.data && event.data.type === 'SKIP_WAITING') {
    console.log('SW: Calling skipWaiting()');
    self.skipWaiting();
  }
});

// Take control of all clients immediately after activation
addEventListener('activate', (event: any) => {
  console.log('SW: Activate event - claiming clients');
  event.waitUntil(
    self.clients.claim().then(() => {
      console.log('SW: Clients claimed successfully');
    })
  );
});
