/*
 * This file (which will be your service worker)
 * is picked up by the build system ONLY if
 * quasar.config file > pwa > workboxMode is set to "InjectManifest"
 *
 * Based on the old site's sw-source.ts - battle tested and working!
 */

/* eslint-disable */
declare const self: any;

import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst } from 'workbox-strategies';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';
import { RangeRequestsPlugin } from 'workbox-range-requests';

// Precache all assets generated by Quasar
precacheAndRoute(self.__WB_MANIFEST);

// Cache video files (if any)
registerRoute(
  ({ request }) => {
    const { destination } = request;
    return destination === 'video';
  },
  new CacheFirst({
    plugins: [
      new CacheableResponsePlugin({
        statuses: [200]
      }) as any,
      new RangeRequestsPlugin() as any,
    ],
  }),
);

// Listen for SKIP_WAITING message (EXACTLY like old site!)
addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});
