[build]
  publish = "dist/pwa"
  command = "npm install && quasar build -m pwa"

[build.environment]
  NODE_VERSION = "20"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

# Cache static assets
[[headers]]
  for = "/assets/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Service Worker - don't cache
[[headers]]
  for = "/sw.js"
    [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/service-worker.js"
    [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

# Manifest
[[headers]]
  for = "/manifest.json"
    [headers.values]
    Cache-Control = "public, max-age=86400"

